Added coverage requirement 95% to test failure

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -64,7 +64,11 @@ jobs:
             coverage=$(jq '.total.lines.pct' coverage/coverage-summary.json)
             color=$(echo "$coverage < 80" | bc | awk '{if ($1) print "red"; else print "green"}')
             curl -s -X POST "https://pizza-factory.cs329.click/api/badge/${{ secrets.NET_ID }}/jwtpizzaservicecoverage?label=Coverage&value=$coverage%25&color=$color" -H "authorization: bearer ${{ secrets.FACTORY_API_KEY }}"
-            
+            if (( $(echo "$coverage < 95" | bc -l) )); then
+              echo "Test coverage ($coverage%) is below the required threshold (95%)."
+              exit 1
+            fi
+
       - name: set version
         id: set_version
         run: |
